# Generated by Django 4.1.5 on 2023-02-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_app', '0003_alter_profile_bio_alter_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='mediaFiles/images/mypic.png', upload_to='Profile/images'),
        ),
    ]
