# Generated by Django 4.1.5 on 2023-02-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_app', '0004_alter_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='/media/mediaFiles/images/mypic.png', upload_to='Profile/images'),
        ),
    ]
